import type { ScientistProfile, IntentAsset, ActivityLog } from '@/types';

export const STORACHA_SPACE_DID = 'did:key:z6MktDavuL1M2VdtHe2nVnhCaD8CiTmchWmyn8x2sEPbfvey';

export const MOCK_SCIENTISTS: ScientistProfile[] = [
  {
    id: 'sci_001',
    fullName: 'Dr. Evelyn Reed',
    email: 'evelyn.reed@stanford.edu',
    handle: '@evelyn_reed',
    affiliation: 'Stanford University',
    bio: 'Specializing in cellular senescence and cardiac tissue regeneration. PI at the Reed Lab focusing on translational approaches to reverse age-related fibrosis using novel mRNA delivery systems.',
    status: 'approved',
    tags: ['#Longevity', '#AI-Bio', '#Tier-1'],
    orcidId: '0000-0002-1234-5678',
    agentNftId: 'ERC8004-ID #4092',
    agentDid: 'did:web:aurasci.network:agents:erc8004-id-4092',
    agentManifestCid: 'QmAgentManifestReed4092abcdefghijklmnopqrstu',
    reputationScore: 98,
    walletAddress: '0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
  },
  {
    id: 'sci_002',
    fullName: 'Dr. Marcus Chen',
    email: 'marcus.chen@mit.edu',
    handle: '@m_chen_neuro',
    affiliation: 'MIT',
    bio: 'Computational neuroscientist working on brain-computer interfaces and neural decoding algorithms. Leading research in non-invasive neural signal processing for cognitive enhancement.',
    status: 'approved',
    tags: ['#Neuroscience', '#AI-Bio', '#Tier-1'],
    orcidId: '0000-0003-8765-4321',
    agentNftId: 'ERC8004-ID #5137',
    agentDid: 'did:web:aurasci.network:agents:erc8004-id-5137',
    agentManifestCid: 'QmAgentManifestChen5137abcdefghijklmnopqrstu',
    reputationScore: 95,
    walletAddress: '0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c',
  },
  {
    id: 'sci_003',
    fullName: 'Dr. Aria Patel',
    email: 'aria.patel@caltech.edu',
    handle: '@ariapatel_gen',
    affiliation: 'Caltech',
    bio: 'Genomics researcher focused on CRISPR-based gene therapies for rare genetic disorders. Pioneer in high-throughput screening methods for guide RNA optimization.',
    status: 'approved',
    tags: ['#Genomics', '#DeSci', '#Tier-2'],
    orcidId: '0000-0001-9999-8888',
    agentNftId: 'ERC8004-ID #3861',
    agentDid: 'did:web:aurasci.network:agents:erc8004-id-3861',
    agentManifestCid: 'QmAgentManifestPatel3861abcdefghijklmnopqrstu',
    reputationScore: 91,
    walletAddress: '0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d',
  },
];

export const MOCK_INTENTS: IntentAsset[] = [
  {
    id: 'intent_001',
    scientistId: 'sci_001',
    title: 'Targeting Senescent Cells to Reverse Cardiac Fibrosis',
    ticker: '$CELL-01',
    coreHypothesis: 'Targeting senescent cells to reverse cardiac fibrosis by innovating senescent cell elimination pathways. Our approach involves developing a novel mRNA-based therapeutic that selectively identifies and clears senescent cardiomyocytes, reducing fibrotic tissue accumulation and restoring cardiac function in aged hearts.',
    evidenceLinks: ['https://github.com/reedlab/cardiac-senescence', 'https://arxiv.org/abs/2401.12345'],
    fundingGoalUSDC: 150000,
    escrowedAmountUSDC: 120000,
    status: 'published',
    aiScore: 94,
    tags: ['#Longevity', '#AI-Bio', '#Tier-1'],
    supporterCount: 2500,
    boostScore: 850,
    trendingRank: 1,
    ipfsCid: 'QmXyZ7a8Bk9Lm2Np4Qr6Ts1Uv3Wx5Yz0Ab2Cd4Ef6Gh8Ij',
    agentId: 'ERC8004-ID #4092',
    agentReputation: 98,
    agentManifestCid: 'QmAgentManifestReed4092abcdefghijklmnopqrstu',
    registrationTxHash: '0xabc123def456789012345678901234567890123456789012345678901234abcd',
    resourceAsks: [{ type: 'compute', description: 'H100 GPU Hours for molecular simulation', quantity: '500 H100 Hrs' }],
    backers: [{ id: 'backer_001', name: 'Advaita Labs' }],
    patrons: [
      { id: 'patron_001', name: 'Alice W.', amountUSDC: 50000, escrowTxHash: '0x1111...aaaa', walletAddress: '0xalice...' },
      { id: 'patron_002', name: 'Bob K.', amountUSDC: 30000, escrowTxHash: '0x2222...bbbb' },
      { id: 'patron_003', name: 'Carol M.', amountUSDC: 25000, escrowTxHash: '0x3333...cccc' },
      { id: 'patron_004', name: 'David L.', amountUSDC: 15000, escrowTxHash: '0x4444...dddd' },
    ],
    milestones: [
      {
        id: 'ms_001_1', intentId: 'intent_001', order: 1, label: 'M1', sublabel: 'Dataset',
        estTime: '3 months',
        objective: 'Compile comprehensive senescent cell biomarker dataset from cardiac tissue samples',
        deliverables: 'Published dataset on GitHub with 10,000+ annotated samples',
        verificationCriteria: 'Dataset passes quality audit with >95% annotation accuracy',
        releaseAmountUSDC: 40000, status: 'in_progress',
        ipfsCid: 'QmMs1Ds3At5Bc7Ce9Df1Eg3Fh5Gi7Hj9Ik1Jl3Km5Ln7Mo',
        agentId: 'ERC8004-ID #4092', agentReputation: 98,
        verificationTxHash: '0xverify001...',
        validationRegistryEntry: 'VALREG-0x001',
      },
      {
        id: 'ms_001_2', intentId: 'intent_001', order: 2, label: 'M2', sublabel: 'in-Vitro',
        estTime: '6 months',
        objective: 'Demonstrate selective senescent cell clearance in vitro cardiac tissue models',
        deliverables: 'Published results showing >70% senescent cell reduction',
        verificationCriteria: 'Peer-reviewed preprint with reproducible protocol',
        releaseAmountUSDC: 55000, status: 'locked',
        ipfsCid: 'QmVt2Iv4Jw6Kx8Ly0Mz2Na4Ob6Pc8Qd0Re2Sf4Tg6Uh8Vi',
        agentId: 'ERC8004-ID #4092', agentReputation: 98,
      },
      {
        id: 'ms_001_3', intentId: 'intent_001', order: 3, label: 'M3', sublabel: 'in-Vivo',
        estTime: '12 months',
        objective: 'Validate therapeutic efficacy in murine cardiac fibrosis model',
        deliverables: 'Animal study data showing significant fibrosis reduction',
        verificationCriteria: 'Statistical significance p<0.05 in primary endpoints',
        releaseAmountUSDC: 55000, status: 'locked',
        ipfsCid: 'QmWu3Jv5Kw7Lx9My1Nz3Ob5Pc7Qd9Re1Sf3Tg5Uh7Vi9Wj',
        agentId: 'ERC8004-ID #4092', agentReputation: 98,
      },
    ],
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'intent_002',
    scientistId: 'sci_002',
    title: 'Non-Invasive Neural Decoding for Cognitive Enhancement',
    ticker: '$NEUR-01',
    coreHypothesis: 'Developing a novel non-invasive neural decoding algorithm that leverages transformer architectures to interpret EEG signals with unprecedented accuracy, enabling real-time cognitive state monitoring and targeted neurofeedback for enhanced learning and memory consolidation.',
    evidenceLinks: ['https://github.com/chenlab/neural-decode'],
    fundingGoalUSDC: 200000,
    escrowedAmountUSDC: 45000,
    status: 'published',
    aiScore: 87,
    tags: ['#Neuroscience', '#AI-Bio', '#Tier-1'],
    supporterCount: 890,
    boostScore: 620,
    trendingRank: 3,
    ipfsCid: 'QmAb1Cd3Ef5Gh7Ij9Kl1Mn3Op5Qr7St9Uv1Wx3Yz5Aa7Bc',
    agentId: 'ERC8004-ID #5137',
    agentReputation: 95,
    agentManifestCid: 'QmAgentManifestChen5137abcdefghijklmnopqrstu',
    registrationTxHash: '0xdef456789012345678901234567890123456789012345678901234567890abcd',
    resourceAsks: [
      { type: 'compute', description: 'A100 GPU for model training', quantity: '1000 A100 Hrs' },
      { type: 'data', description: 'EEG dataset access', quantity: '50TB Neural Data' },
    ],
    backers: [{ id: 'backer_002', name: 'NeuroTech Collective' }],
    patrons: [
      { id: 'patron_005', name: 'Elena S.', amountUSDC: 25000, escrowTxHash: '0x5555...eeee' },
      { id: 'patron_006', name: 'Frank J.', amountUSDC: 20000, escrowTxHash: '0x6666...ffff' },
    ],
    milestones: [
      {
        id: 'ms_002_1', intentId: 'intent_002', order: 1, label: 'M1', sublabel: 'Dataset',
        estTime: '4 months',
        objective: 'Curate and preprocess multi-subject EEG dataset for decoder training',
        deliverables: 'Cleaned dataset with 500+ hours of annotated EEG recordings',
        verificationCriteria: 'Dataset published with documented preprocessing pipeline',
        releaseAmountUSDC: 60000, status: 'in_progress',
        ipfsCid: 'QmNr2Os4Pt6Qu8Rv0Sw2Tx4Uy6Vz8Wa0Xb2Yc4Zd6Ae8Bf',
        agentId: 'ERC8004-ID #5137', agentReputation: 95,
      },
      {
        id: 'ms_002_2', intentId: 'intent_002', order: 2, label: 'M2', sublabel: 'Model',
        estTime: '8 months',
        objective: 'Train and validate transformer-based neural decoder achieving >85% accuracy',
        deliverables: 'Open-source model with benchmark results',
        verificationCriteria: 'Accuracy verified on held-out test set by independent reviewer',
        releaseAmountUSDC: 80000, status: 'locked',
        ipfsCid: 'QmOr3Ps5Qt7Ru9Sv1Tw3Ux5Vy7Wz9Xa1Yb3Zc5Ad7Be9Cf',
        agentId: 'ERC8004-ID #5137', agentReputation: 95,
      },
      {
        id: 'ms_002_3', intentId: 'intent_002', order: 3, label: 'M3', sublabel: 'Trial',
        estTime: '14 months',
        objective: 'Conduct pilot human study demonstrating cognitive enhancement',
        deliverables: 'IRB-approved study results with 30+ participants',
        verificationCriteria: 'Statistically significant improvement in cognitive metrics',
        releaseAmountUSDC: 60000, status: 'locked',
        ipfsCid: 'QmPr4Qt6Ru8Sv0Tw2Ux4Vy6Wz8Xa0Yb2Zc4Ad6Be8Cf0Dg',
        agentId: 'ERC8004-ID #5137', agentReputation: 95,
      },
    ],
    createdAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'intent_003',
    scientistId: 'sci_003',
    title: 'CRISPR Guide RNA Optimization via High-Throughput Screening',
    ticker: '$GENE-01',
    coreHypothesis: 'Applying machine learning-driven high-throughput screening to identify optimal CRISPR guide RNAs for rare genetic disorders, reducing off-target effects by 90% compared to current computational prediction methods.',
    evidenceLinks: ['https://github.com/patellab/crispr-screen'],
    fundingGoalUSDC: 100000,
    escrowedAmountUSDC: 10000,
    status: 'published',
    aiScore: 79,
    tags: ['#Genomics', '#DeSci', '#Tier-2'],
    supporterCount: 340,
    boostScore: 280,
    ipfsCid: 'QmDe5Ef7Fg9Gh1Hi3Ij5Jk7Kl9Lm1Mn3No5Op7Pq9Qr1Rs',
    agentId: 'ERC8004-ID #3861',
    agentReputation: 91,
    agentManifestCid: 'QmAgentManifestPatel3861abcdefghijklmnopqrstu',
    registrationTxHash: '0x789012345678901234567890123456789012345678901234567890123456abcd',
    resourceAsks: [{ type: 'equipment', description: 'Lab equipment rental', quantity: '6 months access' }],
    backers: [],
    patrons: [{ id: 'patron_007', name: 'Grace H.', amountUSDC: 10000, escrowTxHash: '0x7777...gggg' }],
    milestones: [
      {
        id: 'ms_003_1', intentId: 'intent_003', order: 1, label: 'M1', sublabel: 'Screen',
        estTime: '3 months',
        objective: 'Complete high-throughput screening of 100,000+ guide RNA candidates',
        deliverables: 'Screening results and ranked guide RNA database',
        verificationCriteria: 'Database published with full experimental protocols',
        releaseAmountUSDC: 35000, status: 'in_progress',
        ipfsCid: 'QmSt3Tu5Uv7Vw9Wx1Xy3Yz5Za7Ab9Bc1Cd3De5Ef7Fg9Gh',
        agentId: 'ERC8004-ID #3861', agentReputation: 91,
      },
      {
        id: 'ms_003_2', intentId: 'intent_003', order: 2, label: 'M2', sublabel: 'Validate',
        estTime: '7 months',
        objective: 'Validate top 50 guide RNAs in cell line models',
        deliverables: 'Validation data showing off-target reduction metrics',
        verificationCriteria: 'Independent lab replication of top 10 candidates',
        releaseAmountUSDC: 35000, status: 'locked',
        ipfsCid: 'QmTu4Uv6Vw8Wx0Xy2Yz4Za6Ab8Bc0Cd2De4Ef6Fg8Gh0Hi',
        agentId: 'ERC8004-ID #3861', agentReputation: 91,
      },
      {
        id: 'ms_003_3', intentId: 'intent_003', order: 3, label: 'M3', sublabel: 'Publish',
        estTime: '10 months',
        objective: 'Publish ML model and optimized guide RNA library',
        deliverables: 'Open-source ML model + curated guide RNA database',
        verificationCriteria: 'Peer-reviewed publication and community adoption metrics',
        releaseAmountUSDC: 30000, status: 'locked',
        ipfsCid: 'QmUv5Vw7Wx9Xy1Yz3Za5Ab7Bc9Cd1De3Ef5Fg7Gh9Hi1Ij',
        agentId: 'ERC8004-ID #3861', agentReputation: 91,
      },
    ],
    createdAt: Date.now() - 21 * 24 * 60 * 60 * 1000,
  },
];

const now = Date.now();

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  { id: 'log_1', timestamp: now - 120_000, type: 'patronage', message: '💰 David L. funded 15,000 USDC to $CELL-01 via EIP-8183 Escrow', ticker: '$CELL-01', intentId: 'intent_001', txHash: '0x4444...dddd' },
  { id: 'log_2', timestamp: now - 300_000, type: 'ai_verified', message: '🛡️ ERC-8004 Agent #5137 verified $NEUR-01 M1. EIP-8183 Escrow Unlocked.', ticker: '$NEUR-01', intentId: 'intent_002', txHash: '0xverify002...' },
  { id: 'log_3', timestamp: now - 600_000, type: 'ipfs_pinned', message: '📦 $CELL-01 proof artifact pinned to IPFS via Storacha', ticker: '$CELL-01', intentId: 'intent_001', ipfsCid: 'QmMs1Ds3At5Bc7Ce9Df1Eg3Fh5Gi7Hj9Ik1Jl3Km5Ln7Mo' },
  { id: 'log_4', timestamp: now - 900_000, type: 'proof_submitted', message: '📄 Dr. Evelyn Reed submitted proof for $CELL-01 M1 (IPFS pinned)', ticker: '$CELL-01', intentId: 'intent_001' },
  { id: 'log_5', timestamp: now - 1_200_000, type: 'x402_payment', message: '⚡ x402 micropayment: 0.50 USDC for $CELL-01 research data access', ticker: '$CELL-01', intentId: 'intent_001', txHash: '0xx402...' },
  { id: 'log_6', timestamp: now - 1_500_000, type: 'agent_registered', message: '🤖 ERC-8004 Agent #3861 registered (NFT minted). Manifest on IPFS.', ticker: '$GENE-01', intentId: 'intent_003', txHash: '0x789012...abcd' },
  { id: 'log_7', timestamp: now - 1_800_000, type: 'patronage', message: '💰 Elena S. funded 25,000 USDC to $NEUR-01 (EIP-8183 Escrow)', ticker: '$NEUR-01', intentId: 'intent_002', txHash: '0x5555...eeee' },
  { id: 'log_8', timestamp: now - 2_400_000, type: 'escrow_released', message: '🔓 EIP-8183 Escrow released: 40,000 USDC → Dr. Reed ($CELL-01 M0)', ticker: '$CELL-01', intentId: 'intent_001', txHash: '0xrelease001...' },
  { id: 'log_9', timestamp: now - 3_000_000, type: 'intent_published', message: '🧬 $CELL-01 published on-chain. Intent JSON pinned to IPFS/Storacha.', ticker: '$CELL-01', intentId: 'intent_001', ipfsCid: 'QmXyZ7a8Bk9Lm2Np4Qr6Ts1Uv3Wx5Yz0Ab2Cd4Ef6Gh8Ij' },
];
